version: '3.7'

services:
  ubi_db:
    image: postgres:12
    environment:
      - POSTGRES_USER=ubi
      - POSTGRES_PASSWORD=ubi4all
      - POSTGRES_DB=ubi
    volumes: 
      - ubi_dev:/var/lib/postgresql/data/
    ports:
      - 7000:5432
    container_name: ubi_db
    restart: unless-stopped

volumes:
  ubi_dev: